services:
    #Security
    asquel.api_key_bundle.authenticator:
        class: AsQuel\ApiKeyBundle\Security\Authenticator
        arguments:
            - @asquel.api_key_bundle.request_matcher
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }

    asquel.api_key_bundle.request_matcher:
        class: Symfony\Component\HttpFoundation\RequestMatcher
        public: false